variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_key_name" {}
variable "aws_key_path" {}
variable "private_ssh_key" {}
variable "vpc_id" {}
variable "vpc_region" {}
variable "az" {}
variable "subnet-private" {}
variable "subnet-private_cidr" {}
variable "subnet-public" {}
variable "subnet-public_cidr" {}
variable "ssh_access_sg" {}
variable "rhel_ami" {}
